import cv2
import numpy as np

cap = cv2.VideoCapture("dog.mp4") # videoyu çekiyoruz...

while(1):
    _,frame = cap.read() # çektiğimiz videoyu okuyarak frame değişkeninde tutuyoruz...
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV) # video rgb olduğu için renk takibi yapılamıyor o yüzden hsvye çeviriyoruz...
    sensitivity = 15 # hassaslık değeri...
    lower_white = np.array([0,0,255-sensitivity]) # beyaz rengin alt değeri...
    upper_white = np.array([255,sensitivity,255]) # beyazın üst değeri...
    mask = cv2.inRange(hsv,lower_white,upper_white) # maskeleme yapar...
    res = cv2.bitwise_and(frame,frame,mask=mask) # cv2.bitwise_and() # maskelemenin doğru olması için res işlemi yapıyoruz(ikili döngü içerir)...

    cv2.imshow("frame",frame) # orjinal videoyu gösterir...
    cv2.imshow("mask",mask)  # maskelenen videoyu gösterir...
    cv2.imshow("result",res) # beyaz renkleri takip edeni gösterir.Yani sonucu gösterir...

    k = cv2.waitKey(5) & 0xFF
    if k==27:
        break