import cv2

img = cv2.imread("contour.png") # resmi okur...

gray = cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY) # resmi gri hale çevirir...

_,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY) # resmi treshler...

M = cv2.moments(thresh) # resimle ilgili bilgileri sözlük yapısında tutar. Bu sözlükteki bilgileri kullanarak resmin ağırlık merkezini bulucaz...

print(M)

X = int(M["m10"]/M["m00"]) # x koordinatını bulur...
Y = int(M["m01"]/M["m00"]) # y koordinatını bulur...

cv2.circle(img,(X,Y),5,(0,255,0),-1) # resmin merkezine çember çizer...

cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

