import cv2
import numpy as np

img1 = cv2.imread("resim1.jpg")
img2 = cv2.imread("resim2.jpg")

# birinci ve ikinci resimlerin boyutları aynı olmadığı için şimdi boyutlarını öğrenme ve boyutlarını eşitlemeyi yapacağız:
print("firt image",img1.shape) # birinci resmin boyut bilgisini verir...
print("second image",img2.shape) # ikinci resmin boyut bilgisini verir...

img3 = img1[0:452,0:640]# birinci resmin yeni boyutunu(2.resme göre boyutlandırıldı) yeni bir değişkende tuttuk...
print(img3.shape)# birinci resmin yeni boyutunu yazdırır...

dst = cv2.addWeighted(img2,0.6,img3,0.4,0)# iki resmi üst üste ekler.Sırayla parametreler:(ana resim/ana resim yoğunluğu/eklenecek resim/eklenecek resim yoğunluğu/)NOT:ana resim yoğunluğu ve eklenecek resim yoğunlukları toplamı her zaman 1 olmalıdır...
cv2.imshow("dst",dst) # eklenmiş resmi gösterir...

cv2.waitKey(0)
cv2.destroyAllWindows()