import cv2

img = cv2.imread('helikopter.jpg',1) #resmin okunmasını sağlar,ilk parametre resmin adresini ikincisi resmin rengi ile ilgili parametreyi alır...
cv2.imshow('RESIM',img) # okunan resmin ekranda görünmesini sağlar. İlk parametreye açılan pencerenin ismi yazılır, ikinci parametreye okunan resmin değişkeni yazılır...

cv2.waitKey(0) # bir tuşa basılana kadar ekranda kalmasını sağlar...
cv2.destroyAllWindows()  # tuşa bastıktan sonra tüm pencereleri kapatır...