import cv2

yVid = cv2.VideoCapture('sokak.mp4') #videonun yakalanmasını sağlar. İçindeki parametre videonun adresidir(eğer parametreye 0 yazarsak webcam'i açar)...

while(True):
    deger,kare = yVid.read() # videonun okunmasını sağlar.'deger' değişkeni videonun çalışıp çalışmadığını tutar .alışırsa 1 döndürür. 'kare' değişkenide videoyu kare kare resimlere atar...
    cv2.imshow('Sehir Isiklari',kare) # videodaki kare kare alınan resimleri döngüye sokup göstermeyi sağlar. Birinci parametre Açılan ekranın ismini alır ikinci parametrede döngüye sokulacak resim karelerini alır...

    if cv2.waitKey(1) & 0xFF == ord('w'):
        break

yVid.release() #videonun serbest kalmasını sağlar...
cv2.destroyAllWindows() #tüm pencereleri kapatır...
