import cv2
import numpy as np

img = cv2.imread("helikopter.jpg")

row,col,kanal = img.shape # resmin satır değerini row, sütun değerini col ve kanal değerini kanal değişkenine atar...

print(row) # resmin satır değerini yazdırır...
print(col) # resmin sütun değerini yazdırır...
print(kanal) # resmin kanal(rgb) değerinin yazdırır...

M = np.float32([[1,0,50],[0,1,100]]) # bu bir matris formülüdür ve bu formüldeki 50(x) ve 100(y) sayılarının değerlerini değiştirerek açılan pencerede x ve y ekseni yönünde resmi kaydırmamızı sağlar...

dst = cv2.warpAffine(img,M,(col,row)) # resmin kaydırılmış halini dst değişkenine atar. Eşitliğin sağındaki fonksiyon resmin kaymasını sağlar. Aldığı değerler sırayla (kaydırılacak resim/kaydırılma miktarı/açılacak pencerenin satır ve sütun boyutlarıdır(burda açılacak pencerenin boyutlarını resmin ana boyutuyla aynı olsun diye resmin boyutları girilmiş))...

cv2.imshow("dst",dst) # kaydırılmış resmi gösterir...

cv2.waitKey(0)
cv2.destroyAllWindows()
